---
- name: "Get columns"
  ansible.builtin.uri:
    timeout: 90
    url: "https://api.github.com/graphql"
    return_content: true
    headers:
      Authorization: "bearer {{ GITHUB_TOKEN }}"
    method: POST
    body_format: json
    body:
      query: '{{ lookup("template", "query_columns.graphql") }}'
  register: COLUMNS_JSON
- name: "Setup GitHub columns JSON string"
  set_fact:
    COLUMNS_JSON_STR: "{{ ('{\"' + PROJECT.title + '_COLUMNS\":' + (COLUMNS_JSON.json.data.organization.projectV2.field.options | string) + '}') }}"
- name: "Get column"
  include_role:
    name: inspire_column
  vars: 
    COLUMN_NAME: "{{ ANSIBLE_COLUMN.name }}"
    COLUMNS: "{{ COLUMNS_JSON.json.data.organization.projectV2.field.options }}"
  loop: "{{ COLUMNS_JSON.json.data.organization.projectV2.field.options }}"
  loop_control:
    loop_var: ANSIBLE_COLUMN
