---

# Create Role Labels

- name: "Create role label"
  include_role:
    name: inspire_label
  vars: 
    LABEL_NAME: "{{ ROLE_DATA.ROLE_ID }}"
    LABEL_DESCRIPTION: "{{ ROLE_DATA.ROLE_DESCRIPTION }}"
    ORGANIZATION_ID: "{{ REPO_JSON.json.data.organization.id }}"
    FILTER_CARD: Ignore
    CARD_NAME: None
  loop: "{{ HACKATHON_ROLES }}"
  loop_control:
    loop_var: ROLE_DATA

# Create Skill Labels

- name: "Create skill label"
  include_role:
    name: inspire_label
  vars: 
    LABEL_NAME: "{{ ROLE_DATA.SKILL_ID }}"
    LABEL_DESCRIPTION: "{{ ROLE_DATA.SKILL_DESCRIPTION }}"
    ORGANIZATION_ID: "{{ REPO_JSON.json.data.organization.id }}"
    FILTER_CARD: Ignore
    CARD_NAME: None
  loop: "{{ HACKATHON_ROLES }}"
  loop_control:
    loop_var: ROLE_DATA

- name: "Create columns"
  include_role:
    name: inspire_columns
  when: FILTER_STATIC is not defined or FILTER_STATIC != 'true'
