---
- name: Install the opendatapolicing source code and watch service on the target. 
  hosts: localhost
  connection: local
  vars_files:
    - "/usr/local/src/team19-hackathon-2021/vaults/{{ VAULT_ID }}/vault"
  roles:
    - generate_static_classes
