---
- name: Setup Inspire GitHub projects. 
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.local/src/fiware-hackathon-2023/vaults/fiware-2023/vault"
  roles:
    - inspire_hackathon
  tasks:
    - name: "Moo! Your hackathon is ready! "
      debug:
        msg: ""

