---
- name: "Get column by name {{ COLUMN_NAME | default(omit) }}"
  set_fact: {"COLUMN_{{ ANSIBLE_COLUMN.name | regex_replace('[^\\w]', '_') }}": "{{ COLUMNS | json_query(QUERY) | first | default(omit) }}"}
  vars: 
    QUERY: "[?name == '{{ COLUMN_NAME }}']"

- name: "Get cards"
  include_role:
    name: inspire_cards
  vars: 
    COLUMN: "{{ lookup('vars', 'COLUMN_' + (ANSIBLE_COLUMN.name | regex_replace('[^\\w]', '_'))) | default(omit) }}"
  when: FILTER_COLUMN is not defined or FILTER_COLUMN == COLUMN_NAME
