---
- block:
    - name: "Generate body of issue"
      set_fact:
        GENERATED_ISSUE_BODY: "{{ lookup('template', DEFAULT_ISSUE_TEMPLATE) }}"
    - name: "Create issue"
      include_role:
        name: inspire_issue
  vars: 
    ISSUE_LABEL: "{{ SMART_DATA_MODEL.MODEL_NAME }}"
    ISSUE_TITLE: "{{ DEFAULT_ISSUE_TITLE }}"
    ISSUE_REPO_NAME: "{{ REPO.name }}"
    ISSUE_MISSION: "{{ DEFAULT_ISSUE_MISSION }}"
    OVERRIDE_ISSUE_BODY: "{{ GENERATED_ISSUE_BODY }}"
    ISSUE_LABELS: "{{ DEFAULT_ISSUE_LABELS }}"
