- name: Setup issue vars for Java Class {{ JAVA_CLASS.classeNomSimple_enUS_stored_string }}
  set_fact: 
    ISSUE_LABEL: "{{ JAVA_CLASS.hackathonLabel_stored_string | default('create_java_class_' ~ JAVA_CLASS.classeNomSimple_enUS_stored_string) }}"
    ISSUE_TITLE: "{{ JAVA_CLASS.hackathonTitle_stored_string | default(JAVA_CLASS.hackathonMission_stored_string) }}"
    ISSUE_MISSION: "{{ JAVA_CLASS.hackathonMission_stored_string | default(JAVA_CLASS.classeNomSimple_enUS_stored_string) }}"
    ISSUE_LABELS: "{{ JAVA_CLASS.hackathonLabels_stored_string | default('') | regex_findall('\\w[^,]*\\w') }}"
- name: Setup ANSIBLE_ISSUE var
  set_fact: 
    ANSIBLE_ISSUE:
      ISSUE_LABEL: "{{ ISSUE_LABEL }}"
      ISSUE_TITLE: "{{ ISSUE_TITLE }}"
      ISSUE_MISSION: "{{ ISSUE_MISSION }}"
      ISSUE_LABELS: "{{ ISSUE_LABELS }}"
- name: "Get issue by name {{ ISSUE_LABEL | default(omit) }}"
  set_fact: {"ISSUE_{{ ANSIBLE_ISSUE.ISSUE_LABEL | regex_replace('[^\\w]', '_') }}": "{{ ISSUES | json_query(QUERY) | first | default(omit) }}"}
  vars: 
    QUERY: "[?labels[?name == '{{ ISSUE_LABEL }}']]"
- name: Query Apache Solr for all Java class parts
  uri: 
    url: "http://localhost:8983/solr/computate/select?rows=200&q=*:*&fq=-partEstClasse_indexed_boolean:true&fq={{ ANSIBLE_PROJECT.SOLR_APP_NAME }}&fq=classeNomCanonique_enUS_indexed_string:{{ JAVA_CLASS.classeNomCanonique_enUS_stored_string }}"
  register: CLASS_PARTS_JSON
- name: "Generate body of issue"
  set_fact:
    GENERATED_ISSUE_BODY: "{{ lookup('template', 'issue.md') }}"
- name: "Create issue"
  include_role:
    name: inspire_issue
  vars: 
    ISSUE_LABEL: "{{ ANSIBLE_ISSUE.ISSUE_LABEL }}"
    ISSUE_TITLE: "{{ ANSIBLE_ISSUE.ISSUE_TITLE }} Skills: ..."
    ISSUE_REPO_NAME: "{{ ANSIBLE_PROJECT.GITHUB_REPO_NAME }}"
    ISSUES: "{{ lookup('vars', ANSIBLE_PROJECT.PROJECT_NAME + '_ISSUES') }}"
    OVERRIDE_ISSUE_BODY: "{{ GENERATED_ISSUE_BODY }}"
    ISSUE_LABELS: "{{ ANSIBLE_ISSUE.ISSUE_LABELS }}"
  tags: 
    - "class{{ JAVA_CLASS.classeNomSimple_enUS_stored_string }}"
