---
- name: "Create issues for column"
  include_role:
    name: inspire_issues
  vars: 
    CARDS: "{{ lookup('vars', (PROJECT.title | regex_replace('[^\\w]', '_') ) + '_COLUMN_' + (COLUMN.id | string) + '_CARDS') }}"
