---
- name: "Get cards"
  uri:
    timeout: 90
    url: "https://api.github.com/projects/columns/{{ COLUMN.id }}/cards?per_page=100"
    return_content: true
    headers:
      Authorization: "token {{ GITHUB_TOKEN }}"
      Accept: "application/vnd.github.inertia-preview+json"
  register: CARDS_JSON
- name: "Get column by name {{ COLUMN_NAME | default(omit) }}"
  set_fact: {"{{ PROJECT.name }}_COLUMN_{{ COLUMN.id }}_CARDS": "{{ CARDS_JSON.json }}"}
- name: "Create issues for column"
  include_role:
    name: inspire_issues
  vars: 
    CARDS: "{{ lookup('vars', PROJECT.name + '_COLUMN_' + (COLUMN.id | string) + '_CARDS') }}"
