---
- name: "Get projects"
  ansible.builtin.uri:
    timeout: 90
    url: "https://api.github.com/graphql"
    return_content: true
    headers:
      Authorization: "bearer {{ GITHUB_TOKEN }}"
    method: POST
    body_format: json
    body:
      query: '{{ lookup("template", "query_projects.graphql") }}'
  register: PROJECTS_JSON
- name: "Create projects"
  include_role:
    name: inspire_project
  vars: 
    PROJECTS: "{{ PROJECTS_JSON.json.data.organization.projectsV2.nodes }}"
    ORGANIZATION_ID: "{{ PROJECTS_JSON.json.data.organization.id }}"
  loop: "{{ANSIBLE_PROJECTS}}"
  loop_control:
    loop_var: ANSIBLE_PROJECT
