---
- name: "Get issue by name {{ ISSUE_LABEL | default(omit) }}"
  set_fact: {"ISSUE_{{ ANSIBLE_ISSUE.ISSUE_LABEL | regex_replace('[^\\w]', '_') }}": "{{ ISSUES | json_query(QUERY) | first | default(None) }}"}
  vars: 
    QUERY: "[?labels[?name == '{{ ISSUE_LABEL }}']]"
- name: "Generate body of issue"
  set_fact:
    GENERATED_ISSUE_BODY: "{{ lookup('template', 'issue.md') }}"
  when: OVERRIDE_ISSUE_BODY is not defined
- name: "Generate body of issue"
  set_fact:
    GENERATED_ISSUE_BODY: "{{ OVERRIDE_ISSUE_BODY }}"
  when: OVERRIDE_ISSUE_BODY is defined
- block:
    - name: "Create issue by name {{ ISSUE_LABEL }}"
      connection: local
      ansible.builtin.uri:
        timeout: 90
        url: "https://api.github.com/graphql"
        method: POST
        headers:
          Authorization: "bearer {{ GITHUB_TOKEN }}"
        body_format: json
        body: 
          query: '{{ lookup("template", "create_issue.graphql") }}'
        return_content: true
        status_code: 
          - 200
          - 201
      when: lookup('vars', 'ISSUE', default='') == ''
      register: ISSUE_CREATE_YML
      tags: issue_name
    - name: "Update issue by name {{ ANSIBLE_ISSUE.ISSUE_LABEL }}: PATCH https://api.github.com/repos/{{ GITHUB_ORG }}/{{ ISSUE_REPO_NAME }}/issues/{{ ISSUE.number }}"
      connection: local
      ansible.builtin.uri:
        timeout: 90
        url: "https://api.github.com/graphql"
        method: POST
        headers:
          Authorization: "bearer {{ GITHUB_TOKEN }}"
        body_format: json
        return_content: true
        body: 
          query: '{{ lookup("template", "update_issue.graphql") }}'
        status_code: 
          - 200
      when: lookup('vars', 'ISSUE', default='') != ''
      register: ISSUE_UPDATE_YML
      tags: issue_name
    
    - debug:
        var: ISSUE_CREATE_YML.json
      when: lookup('vars', 'ISSUE', default='') == ''
    - debug:
        var: ISSUE_UPDATE_YML.json
      when: lookup('vars', 'ISSUE', default='') != ''
#    - name: Create card
#      include_role: 
#        name: inspire_card
#      vars: 
#        ISSUE_NUMBER: "{{ ISSUE_CREATE_YML.json.number }}"
#        CARD_CONTENT_ID: "{{ ISSUE_CREATE_YML.json.id }}"
#        CARD_CONTENT_TYPE: "Issue"
#      when: lookup('vars', 'ISSUE', default='') == ''
#    - name: Create card
#      include_role: 
#        name: inspire_card
#      vars: 
#        ISSUE_NUMBER: "{{ ISSUE.number }}"
#        CARD_CONTENT_ID: "{{ ISSUE.id }}"
#        CARD_CONTENT_TYPE: "Issue"
#      when: lookup('vars', 'ISSUE', default='') != ''
  vars:
    ISSUE: "{{ lookup('vars', 'ISSUE_' + (ANSIBLE_ISSUE.ISSUE_LABEL | regex_replace('[^\\w]', '_'))) | default(omit) }}"
